const arrLen = 2

module.exports = {
  'name': 'JavaScript Types',
  'Atomics': Atomics,
  'Array': [1, 2, 3],
  'ArrayBuffer': new ArrayBuffer(arrLen),
  'BigInt': BigInt(123),
  'BooleanTrue': true,
  'BooleanFalse': false,
  'DataView': new DataView(new ArrayBuffer(arrLen)),
  'Date': new Date(),
  'Error': Error('JavaScript Error'),
  'Float32Array': new Float32Array(arrLen),
  'Float64Array': new Float64Array(arrLen),
  'Function': function funky (a, b) {},
  'FunctionAnon': (a, b) => {},
  'FunctionAsync': async function (foo, bar) {},
  'Generator': (function * () {})(),
  'GeneratorFunction': function * (foo, bar) {},
  'Infinity': Infinity,
  'Int16Array': new Int16Array(arrLen),
  'Int32Array': new Int32Array(arrLen),
  'Int8Array': new Int8Array(arrLen),
  'Map': new Map([['foo', 'bar']]),
  'NaN': Number.NaN,
  'null': null,
  'Number': 42,
  'Object': {is: true},
  'Promise': Promise.resolve(),
  'RegEx': /a.long.regexp.that.keeps.giving/,
  'Set': new Set([['foo', 'bar']]),
  'SharedArrayBuffer': new SharedArrayBuffer(arrLen),
  'String': 'The quick brown fox jumps over the lazy dog.',
  'Symbol': Symbol('Symbol Description'),
  'Uint16Array': new Uint16Array(arrLen),
  'Uint32Array': new Uint32Array(arrLen),
  'Uint8Array': new Uint8Array(arrLen),
  'Uint8ClampedArray': new Uint8ClampedArray(arrLen),
  'WeakMap': new WeakMap(),
  'WeakSet': new WeakSet(),
  'undefined': undefined,
}
