const arrLen = 2

module.exports = [
  'JavaScript Types',
  Atomics,
  [1, 2, 3],
  new ArrayBuffer(arrLen),
  BigInt(123),
  true,
  false,
  new DataView(new ArrayBuffer(arrLen)),
  new Date(),
  Error('JavaScript Error'),
  new Float32Array(arrLen),
  new Float64Array(arrLen),
  function funky (a, b) {},
  (a, b) => {},
  async function (foo, bar) {},
  (function * () {})(),
  function * (foo, bar) {},
  Infinity,
  new Int16Array(arrLen),
  new Int32Array(arrLen),
  new Int8Array(arrLen),
  new Map([['foo', 'bar']]),
  Number.NaN,
  null,
  42,
  {is: true},
  Promise.resolve(),
  /a.long.regexp.that.keeps.giving/,
  new Set([['foo', 'bar']]),
  new SharedArrayBuffer(arrLen),
  'The quick brown fox jumps over the lazy dog.',
  Symbol('Symbol Description'),
  new Uint16Array(arrLen),
  new Uint32Array(arrLen),
  new Uint8Array(arrLen),
  new Uint8ClampedArray(arrLen),
  new WeakMap(),
  new WeakSet(),
  undefined,
]
